server:
  port: 8080
  servlet:
    context-path: /user

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  sql:
    init:
      schema-locations: classpath:sql/user/user_schema.sql
      encoding: utf-8
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.transaction.interceptor: trace
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.resource.transaction: DEBUG

jwt:
  header: Authorization
  issuer: play-hooky
  client-secret: ${JWT_SECRET}
  refresh-token-expiry-seconds: 2592000 # 60초 * 60분 * 24시간 * 30일 = 1달
  access-token-expiry-seconds: 86400 # 60초 * 60분 * 24시간 = 1일