server:
  port: 8080
  servlet:
    context-path: /

logging:
  pattern:
    file: '[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n'
  file:
    name: ./logs/newspeed.log
  level:
    root: INFO
    org.springframework.transaction.interceptor: trace
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.resource.transaction: DEBUG
    org.hibernate.orm.jdbc.bind: trace
  logback:
    rollingpolicy:
      max-file-size: 500MB
      file-name-pattern: ./logs/newspeed.%d{yyyy-MM-dd}.%i.log

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 1

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  header: Authorization
  issuer: play-hooky
  client-secret: ${JWT_SECRET}
  refresh-token-expiry-seconds: 2592000 # 60초 * 60분 * 24시간 * 30일 = 1달
  access-token-expiry-seconds: 86400 # 60초 * 60분 * 24시간 = 1일

oauth:
  grant-type: authorization_code
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    auth-url: ${KAKAO_OAUTH_URL}
    user-url: ${KAKAO_USER_URL}
    redirect-uri: ${KAKAO_REDIRECT_URI}
  apple:
    url: ${APPLE_URL}
    client-id: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    key-id: ${APPLE_KEY_ID}
    key: ${APPLE_KEY}
    scope: ${APPLE_SCOPE}
    redirect-uri: ${APPLE_REDIRECT_URI}
    auth-state: ${APPLE_AUTH_STATE}

content:
  youtube:
    url: ${GOOGLE_API_URL}
    key: ${YOUTUBE_KEY}
    videoUrl: ${YOUTUBE_VIDEO_URL}
  instagram:
    url: ${INSTAGRAM_API_URL}
    key: ${INSTAGRAM_KEY}
    userID: ${INSTAGRAM_USER_ID}

browser:
  name: webdriver.chrome.driver
  driver:
    path: classpath:/binary/chromedriver