name: newspeed-server CI 테스트 자동화

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GRADLE_VERSION: 8.3
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: TimeZone을 Asia/Seoul로 설정합니다
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Setup Gradle w/ caching
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Check Code Convention
        run: gradle check

      - name: Check Tests w/ Test Coverage
        run: gradle testWithJacoco

      - name: 테스트 결과를 PR에 코멘트로 등록합니다
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/**/*.xml'

      - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트를 등록합니다
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/*.xml'
          token: ${{ github.token }}

      - name: Add Coverage on Pull Request
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ./build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ github.token }}
          min-coverage-overall: 60
          min-coverage-changed-files: 60
          title: Test Coverage Report
